name: Terraformer
version: 1.0.0
main: io.papermc.terraformer.Terraformer
description: A terraforming and world editing tool.
author: flcristian
website: https://papermc.io
api-version: '1.21.4'

commands:
  terraform:
    description: Main command for the Terraformer plugin
    usage: /<command> [help] for more information
    permission: terraformer.use

permissions:
  terraformer.use:
    description: Allows using the base terraform command
    default: true
  terraformer.mode:
    description: Allows entering terraform mode
    default: op