name: Terraformer
version: 1.4.0
main: ro.flcristian.terraformer.Terraformer
description: A terraforming and world editing tool.
author: flcristian
website: https://github.com/flcristian/terraformer
api-version: '1.21.4'

commands:
  terraform:
    description: Main command for the Terraformer plugin
    usage: /<command> [help] for more information
    permission: terraformer.use
    aliases: [tf]
    subcommands:
      help:
        description: Show help information for terraform command
        usage: /terraform help [page]
      start:
        description: Start terraforming mode
        usage: /terraform start
      stop:
        description: Stop terraforming mode
        usage: /terraform stop
      undo:
        description: Undo last modification
        usage: /terraform undo
      redo:
        description: Redo last modification
        usage: /terraform redo
      brushes:
        description: Show all brush types
        usage: /terraform brushes
      brush:
        description: Set terraforming brush type
        usage: /terraform brush <brush>
        aliases: [b]
      size:
        description: Set terraforming brush size
        usage: /terraform size <size>
        aliases: [s]
      depth:
        description: Set terraforming brush depth
        usage: /terraform depth <depth>
        aliases: [d]
      materials:
        description: Set terraforming materials
        usage: /terraform materials <materials>
        aliases: [m]
      materialmode:
        description: Set terraforming material mode
        usage: /terraform materialmode <mode>
        aliases: [mm]
      materialmodes:
        description: Show all material modes
        usage: /terraform materialmodes
      mask:
        description: Set terraforming mask blocks
        usage: /terraform mask <mask>
        aliases: [mk]
      randomheight:
        description: Toggle random height mode (for foliage brush)
        usage: /terraform randomheight
        aliases: [rh]
      schematic:
        description: List all schematics / Load a schematic
        usage: /terraform schematic <list/load>
        aliases: [schem]
      randomrotation:
        description: Toggle random rotation mode (for schematic brush)
        usage: /terraform randomrotation
        aliases: [rr]
      blockupdates:
        description: Toggle block updates when brushing
        usage: /terraform blockupdates
        aliases: [bu]

permissions:
  terraformer.use:
    description: Allows using the base terraform command
    default: true
  terraformer.mode:
    description: Allows entering terraform mode
    default: op