name: Terraformer
version: 1.0.0
main: io.papermc.terraformer.Terraformer
description: A terraforming and world editing tool.
author: flcristian
website: https://papermc.io
api-version: '1.21.4'

commands:
  terraform:
    description: Main command for the Terraformer plugin
    usage: /<command> [start|stop|undo|redo]
    permission: terraformer.use

permissions:
  terraformer.use:
    description: Allows using the base terraform command
    default: true
  terraformer.start:
    description: Allows using the terraform start command
    default: op
  terraformer.stop:
    description: Allows using the terraform stop command
    default: op
  terraformer.modify:
    description: Allows using undo and redo commands
    default: op